---
# tasks file for ansible-role-mailgraph

- include: install.yml

- include: configure.yml

# Removed this task as mailgraph does not have a 'status' check on it's init script.
#- name: Ensure Mailgraph is started
#  service: name=mailgraph state=started enabled=yes
